version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_NAME=Mulder
      - CPU_COUNT=12
      - MEM_LIMIT=40g
      - PUID=1000
      - PGID=1000
      - RESTART=unless-stopped
      - GAME_PORT=2302
      - STEAM_PORT=2304
      - RCON_PORT=2306
      - GAME_PASSWORD=
      - ADMIN_PASSWORD=
      - RCON_PASSWORD=
      - MOUNT_OVERRIDES=
      - MOD_IDS=3166096719,
      - MODS=
      - AUTO_MODS=false
      - STEAM_APP_ID=1042420
      - UPDATE_SERVER=true
      - UPDATE_MODS=true
      - DEBUG=true
    container_name: mulder-server
    restart: unless-stopped
    ports:
      - "2302:2302"
      - "2302:2302/udp"
      - "2304:2304"
      - "2304:2304/udp"
      - "2306:2306"
    volumes:
      - ./workshop:/server/mods
      - ./server:/server
      - ./profiles/mulder-myserver:/server/profile
      - ./missions/mulder-myserver:/server/mpmissions
      - ./config/mulder-myserver/serverDZ.cfg:/server/serverDZ.cfg:ro
      - ./config/mulder-myserver/beserver_x64.cfg:/server/battleye/beserver_x64.cfg:ro
      - ./steamcmd:/root/.steam
      - /var/run/docker.sock:/var/run/docker.sock
